# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('birthday', models.DateTimeField(auto_now_add=True)),
                ('birthplace', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=13)),
                ('social_number', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to='')),
                ('comment', models.TextField()),
            ],
        ),
    ]
