# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_followup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('f', 'Female'), ('m', 'Male')], max_length=1),
        ),
    ]
