# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_followup', '0002_auto_20180926_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(default='', max_length=254),
        ),
    ]
