# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_followup', '0005_patient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='picture',
            field=models.BinaryField(),
        ),
    ]
