# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 13:48
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import patient_followup.models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_followup', '0008_auto_20181001_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='picture',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media//images/', location='C:\\projets\\web_development\\django\\HCare\\HCare\\media/images/'), upload_to=patient_followup.models.image_directory_path),
        ),
    ]
