# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 14:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_followup', '0009_auto_20181001_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 10, 3, 16, 25, 8, 489082))),
                ('duration', models.IntegerField(default='15')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='appointement',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointements', to='patient_followup.Patient'),
        ),
    ]
