# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-06 18:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_followup', '0011_auto_20181006_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 6, 20, 53, 44, 978706)),
        ),
        migrations.AlterField(
            model_name='appointement',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointements', to='patient_followup.Patient'),
        ),
        migrations.AlterField(
            model_name='medicalexam',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 6, 20, 53, 44, 979704)),
        ),
    ]
