# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-06 19:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_followup', '0012_auto_20181006_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointement',
            old_name='comment',
            new_name='note',
        ),
        migrations.AlterField(
            model_name='appointement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 6, 21, 34, 27, 468022)),
        ),
        migrations.AlterField(
            model_name='appointement',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='appointements', to='patient_followup.Patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalexam',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 6, 21, 34, 27, 470517)),
        ),
    ]
